### ISSUE TITLE
해커톤 한번 출품해볼까요?

### ISSUE THREAD

**Issue by hongregii** [modulersYJ/Gan_Overflow#103]
https://www.prompterday.com

보셨을지 모르겠지만 SKT 해커톤이라고 하네요
주제는 GENAI 서비스입니다

@ABizCho 한번 가보시고 의견 주세요 ~~~

**Comment by ABizCho** [comment]
@hongregii 생각해봤는데 해커톤 출품을 위해선 PLP PDP 기능을 더 뚜렷하게 하고 , 기능의 확장도 고려해봐야 할 것 같아요! 다음주 중 괜찮으시면 한번 대면 어떠십사 하는데, 혹시 괜찮은 날 있으신가요?!
